1. Create a 3x3 array that contains a diagonal of nines.

In [3]:
import numpy as np

arr = np.diag([9,9,9])
arr

array([[9, 0, 0],
       [0, 9, 0],
       [0, 0, 9]])

2. Create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32 (inclusive) and use Boolean indexing to pick out the values that are within 1/2 standard deviations of the mean.

In [9]:
arr1 = np.arange(2,33,2)
#arr1

std = arr1.std()
mean = arr1.mean()

arr1[np.abs(arr1 - mean) <= 0.5 * std]

array([14, 16, 18, 20])

3. Create a 9x9 array of zeros (int)

In [12]:
arr2 = np.zeros([9,9],dtype=int)
arr2

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

4. Ask the user for a number n. Then, use broadcasting to create a n x n
ndarray that has its first column full of ones, its second column full of twos, its third column full of threes, etc…

In [20]:
n = int(input("Please enter a number: "))
customized_arr = np.arange(1,n+1,dtype=int) * np.ones((n,n),dtype=int)
customized_arr
# customized_arr = np.zeros((n,n),dtype=int)
# customized_arr[:]=np.arange(1, n + 1)

Please enter a number: 6


array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])